services:

  helloworld:
    build:
      context: .
      args:
        JAR_FILE: ./target/helloworld.jar
    container_name: helloworld
    ports:
      - '8080:8080'
    extra_hosts:
      - 'chifu168.net:192.168.254.184'